### ISSUE TITLE
Cookie_test doesn't always give/show the right result

### ISSUE THREAD

**Issue by maloumaris** [openstreetmap/openstreetmap-website#1220]
In an email I got a link to sign up for OpenStreetMap (https://www.openstreetmap.org/user/new?cookie_test=true). The website I got showed the sign up page, as expected, but also a message that I didn't have cookies enabled and I should enable them before going further. I've seen this in both Firefox and Chrome, see the attachment for a screen shot of the website in Chrome. I did have cookies enabled however, and simply changing the url to 'https://www.openstreetmap.org/user/new?cookie_test=false' made the message about cookies go away.

I've tried the same thing with cookies disabled. The same website, with the message about cookies being disabled was shown, and now changing the url to 'https://www.openstreetmap.org/user/new?cookie_test=false' did not make the message go away.

Especially the first case is confusing for people who don't know where to change their cookie preferences and whether they should do that, and even more so because the message shouldn't show when cookies are enabled.

![issue_osm](https://cloud.githubusercontent.com/assets/1774471/15394683/95ac651a-1dd4-11e6-952e-ec3802af2ffe.png)

**Comment by tomhughes** [comment]
Sorry, where did you get an email with that URL from?

No email we send should have that link in it - the cookie_test parameter is an internal implementation details, part of us probing for cookies so we can warn the user if they are disabled.

**Comment by maloumaris** [comment]
I got the email from Ready2Help, who invited me for a mapathon for missing maps (and we used OpenStreetMap to do the mapping). I'm not sure where they got the URL from.

**Comment by tomhughes** [comment]
Hmm the correct URL is just https://www.openstreetmap.org/user/new. I think they must have use d a browser that had cookies disabled and then copy and pasted the URL after going to the page.

It could probably be fixed, at the expense of doing an extra reload at the end of the cookie detection routine to remove the parameter from the URL, but it's a pretty obscure edge case.

**Comment by maloumaris** [comment]
I see, when I use https://www.openstreetmap.org/user/new there is indeed no message about the cookies being disabled. It's definitely not a high priority issue, I justed wanted to let you know about the behaviour I've seen, because it might have been something more problematic. Thanks for looking into it, and I'll write Ready2Help to use the correct URL the next time.

**Comment by Firefishy** [comment]
I suspect that any issue here has been fixed a long time ago, maybe in a rails update.

**Comment by tomhughes** [comment]
It does still happen, but only if you launch that URL in a browser that has no OSM cookies.

The odd thing was somebody distributing that URL with the `cookie_test` parameter to other people to use to signup when that URL normally only appears transiently as we test for cookie support.

**Comment by tomhughes** [comment]
There's not really anything we can do here - the whole point of the parameter is to display that message if the URL lands with it and without a cookie so I'm going to close this.
