### ISSUE TITLE
Highlighting objects on mobile

### ISSUE THREAD

**Issue by mmd-osm** [openstreetmap/openstreetmap-website#1663]
I’m opening https://www.openstreetmap.org/way/26904597 on an iPhone 6s in Safari/Chrome. Instead of displaying the object in the map center, it’s shown in the lower left corner. When panning the map the object marker even disappears. In addition there’s a largish grey area where I’d expect a map. Please see the two screenshots below.

![06230697-30b8-4e46-b5d9-66e3db14de16](https://user-images.githubusercontent.com/5842757/32163712-7b1141ce-bd5d-11e7-8d9a-8ef5e5076eed.jpeg)
![3681b74e-5ad4-4942-809c-996f74a0f88d](https://user-images.githubusercontent.com/5842757/32163714-7b315f40-bd5d-11e7-8747-9afa98a6a380.jpeg)

**Comment by mmd-osm** [comment]
BTW: No actual iPhone is required to reproduce this, Firefox Screen size simulation (Ctrl-Shift-M) will do as well. Be sure to select iPhone 6s:

![grafik](https://user-images.githubusercontent.com/5842757/32215647-d25aa900-be22-11e7-8a61-bbf14dd15013.png)

**Comment by HolgerJeromin** [comment]
The disapearing outline is there in chrome/opera on android (blink engine), too. But not in firefox mobile (gecko).

**Comment by HolgerJeromin** [comment]
This is fixed now. Browser update?

**Comment by mmd-osm** [comment]
No it’s not fixed, still the same issue on chrome 63.0 on iPhone

**Comment by HolgerJeromin** [comment]
You are right, sorry. Fixed in Opera 44, but not chrome 63 on android.
But on iOS all browsers uses the safari engine.

**Comment by bryceco** [comment]
In case it’s not clear: this is still broken on safari in iOS.

**Comment by dieterdreist** [comment]
Checking now, it works for notes on iOS (all tiles displayed). There is still an issue if you look at a specific object (/way/123) and close the details the whole map pans approximately one screen width to the left, so that the object you were looking at is off screen

**Comment by carstenhag** [comment]
Broken on chrome beta 77 @ android.

**Comment by dieterdreist** [comment]
it is still broken in iPhone7 with latest Safari and iOS13.1. The tile is not requested, instead a tile is requested that isn't visible at all (only 3 tiles, all of the same column, are requested). This is the whole tile-container:

`<div class="leaflet-tile-container leaflet-zoom-animated" style="z-index: 19; transform: translate3d(0px, 0px, 0px) scale(1);"><img alt="" role="presentation" src="https://c.tile.openstreetmap.org/17/74534/38466.png" class="leaflet-tile leaflet-tile-loaded" style="width: 256px; height: 256px; transform: translate3d(-173px, 171px, 0px); opacity: 1;"><img alt="" role="presentation" src="https://b.tile.openstreetmap.org/17/74534/38465.png" class="leaflet-tile leaflet-tile-loaded" style="width: 256px; height: 256px; transform: translate3d(-173px, -85px, 0px); opacity: 1;"><img alt="" role="presentation" src="https://a.tile.openstreetmap.org/17/74534/38467.png" class="leaflet-tile leaflet-tile-loaded" style="width: 256px; height: 256px; transform: translate3d(-173px, 427px, 0px); opacity: 1;"></div>`
