### ISSUE TITLE
Prevent GPX trace upload form on website from violating API restrictions

### ISSUE THREAD

**Issue by kmpoppe** [openstreetmap/openstreetmap-website#3594]
### Description

As #1702 outlined (with a totally problem), the maximum length for the `description` value of a GPX track is 255 characters as per API restriction.

But, similar to StreetComplete (streetcomplete/streetcomplete#4195), the website does not restrict the maximum length of the input box. As the error message "is too long (maximum is 255 characters)" is only show after the user submits the form, the GPX file has already been completely transferred by the browser, only to be discarded because the API restrictions were violated.

Possible solution: Either use the slightly dated `maxlength` attribute on the `input` box or make a javascript check to not allow the form to be submitted if the description exceeds the maximum allowed characters.

If using a fixed value of 255 feels to static, adding that value in the GET /api/capabilities and using that as a reference for the input fields, should the datamodel ever be expanded (this could also be used for limits on the texts of Note Comments, if they exist).

Thoughts?

K

**Comment by AntonKhorev** [comment]
> Possible solution: Either use the slightly dated `maxlength` attribute on the `input` box or make a javascript check to not allow the form to be submitted if the description exceeds the maximum allowed characters.

Why is `maxlength` dated? It won't let you submit the form with too many characters and it will display the error message.

**Comment by AntonKhorev** [comment]
Same for tags. Each tag is 255 chars max but they are entered comma-separated in a single input. `maxlength` won't help in this case, but `pattern` might work.

**Comment by mmd-osm** [comment]
Fix has been merged, let’s close this issue.

**Comment by AntonKhorev** [comment]
It wasn't fixed for invalid tags and descriptions that are too short. I'm still not sure how short is too short: #3598
