### ISSUE TITLE
"HTML embedding is not available for this map layer" when selecting a vector layer

### ISSUE THREAD

**Issue by fuddl** [openstreetmap/openstreetmap-website#6247]
### Problem

When selecting a vector layer, it is not possible to share an HTML embed:
![Screenshot with an error message shown when selecting a vector layer and choosing to share via embed](https://github.com/user-attachments/assets/e7d85e42-f14e-4bca-acae-27d6e3979a2f)

**Comment by hlfan** [comment]
Given that the `canEmbed` configuration option is only necessary to fix #4273, that should probably be added to the [layers.yml](https://github.com/openstreetmap/openstreetmap-website/blob/master/config/layers.yml).

On the other hand, this bloats embed.js significantly. Can MapLibre be only included when the iframe is requested with a vector layer?

**Comment by 1ec5** [comment]
We could in principle maintain two separate embed pages, one for raster layers and the other for vector layers. But after #6234, this would end up being the only instance of Leaflet anywhere on the site. Any bug in the Leaflet version of the embed map would probably go unnoticed until some third-party site’s users experience it. We might also get feedback about subtle differences between the two versions of the embed map that we wouldn’t otherwise care about if we do a clean migration.

MapLibre gets embedded quite frequently these days. Maybe the bloat is not as big of a deal as it would’ve been in the past?

**Comment by 1ec5** [comment]
So far we’ve been forging ahead with #6234 based on data showing that enough visitors to the homepage have WebGL-capable environments: https://github.com/openstreetmap/openstreetmap-website/issues/6234#issuecomment-3115356831. However, the embed page has a broader audience that might have lower WebGL prevalence. @pnorman, would you be able to run the numbers on the embed page just in case?

Regardless, I still suspect there’s enough of a benefit to being able to support all the featured layers that we should attempt to support sharing the vector layers somehow. I see a few different options, in order of personal preference:

1. Rewrite embed.js.erb to replace leaflet-osm with MapLibre. If [MapLibre detects that WebGL is unsupported](https://maplibre.org/maplibre-gl-js/docs/examples/check-if-webgl-is-supported/), fall back to a basic Leaflet map in the same page that doesn’t rely on leaflet-osm. Enable the embed page for every layer.
2. Write a separate MapLibre-powered embed page to sit alongside [embed.js.erb](https://github.com/openstreetmap/openstreetmap-website/blob/master/app/assets/javascripts/embed.js.erb). Try to wean the latter page off of leaflet-osm. If MapLibre detects that WebGL is unsupported, redirect to the Leaflet-powered page. Connect the share panel to a different embed page depending on the layer, even if that results in differing behavior.
3. Rewrite embed.js.erb to replace leaflet-osm with MapLibre. If MapLibre detects that WebGL is unsupported, fall back to a basic message about WebGL support.

@hlfan @CommanderStorm, can you think of any other options? Do you think the size of MapLibre compared to Leaflet would strongly push us toward option 2 instead of option 1? Can we get away with option 3 without much pushback from Web developers?

**Comment by CommanderStorm** [comment]
I am fine with all.

1. would mean downloading laflet and maplibre, right?
   That seems suboptimal. But if including maplibre 2x in the website "bundle" is not something that is very noticable, maybe this does not matter much.
3. is likely the most compatible and also fairly OK to test.
4. is likely the simplest to maintain, but might break users when they have

Honestly, 1. seems very messy. I would prefer 2. or 3.
If we can go with 3. is a call that depends on how we value legacy compatability vs maintanability.
A bug in 2. would likely go unnoticed for a bit and might be a bit harder to reproduce since it is not immediately clear what happens without looking at the logs.

**Comment by pnorman** [comment]
I'd just go with 3. Otherwise the embed page becomes the only use of leaflet on the site.

If someone using it wants more control over the libraries being used they can use the libraries of their choice without our embed.

**Comment by 1ec5** [comment]
Fair enough. I assume we’d use a similar fallback message as we would on the homepage for the slippy map. Which could be similar to the message when JavaScript is disabled:

https://github.com/openstreetmap/openstreetmap-website/blob/585a0dc871e6c99d7b089ef0996a8feb6cb2f184/config/locales/en.yml#L2607-L2608

**Comment by hlfan** [comment]
Currently only the "report a problem" translations are sent with the embed. Depending on the webgl detection timing that may need to be expanded too.

**Comment by CommanderStorm** [comment]
I am soft-blocking this on https://github.com/openstreetmap/openstreetmap-website/pull/6772 to not work on basically the same thing in two PRs and am going to do a bit of work upstream over the next 1-2 weeks

**Comment by CommanderStorm** [comment]
@hlfan I forgot to link this one. It is resolved

**Comment by hlfan** [comment]
Well, the MapTiler OMT layer still isn't supported, but that apparently is similar to this: https://github.com/openstreetmap/openstreetmap-website/issues/4273#issuecomment-1746643958

**Comment by CommanderStorm** [comment]
MapTiler OMT could be made to work by just pointing it to OpenFreemap, but I think the time is better spend on making Pauls alternative a proper alternative in all features.

I think that was the goal all along, or?
