### ISSUE TITLE
Context menu icons are inconsistent with icons used elsewhere

### ISSUE THREAD

**Issue by gravitystorm** [openstreetmap/openstreetmap-website#6485]
Our [updated context menu](https://github.com/openstreetmap/openstreetmap-website/pull/6410) ships with icons for the various menu items. However, these are inconsistent with the icons used elsewhere in the UI. We should consider whether they can be unified - either by changing the menu, or changing the icons used elsewhere, or perhaps both. Here's the list of inconsistencies:

## Directions

The directions icons used in the sidebar and on the map show pins with play and stop icons. The context menu has a pin with a circle for the start, and a flag for the finish.

<img width="672" height="355" alt="Image" src="https://github.com/user-attachments/assets/515c9a6d-b5cb-472d-8e2a-39906389c69d" />

## Add a Note

The Add a Note menu item has a pencil, the map button has a speech bubble with a plus sign, and the map icon is a blue pin with a plus sign

<img width="672" height="123" alt="Image" src="https://github.com/user-attachments/assets/179f6cbd-d28a-4959-8d62-f3228b005df0" />

## Query features

The Query features menu item is a question mark in a circle, the map button is an arrow with a small question mark. Note that the cursor also changes (using CSS `cursor: help`) but this is platform specific - some platforms show the arrow and small question mark, others show different icons.

<img width="483" height="79" alt="Image" src="https://github.com/user-attachments/assets/257710c4-1782-4715-afb2-a0be81f2a54b" />

**Comment by Hiteshpy07** [comment]
hey @gravitystorm , i noticed all the inconsitancys you have listed , but now it is resolved i guess, i cannot spot them any more , if there is any more , i can fix it

**Comment by pablobm** [comment]
@Hiteshpy07 - What did you check? There has been no change and the inconsistencies are still present as listed in the issue description. Therefore you can look into them 🙂

**Comment by aNsHuL5217** [comment]
Hi @gravitystorm  and @pablobm ,

I have checked the website and confirmed that the icon inconsistencies are still present as described in the issue.

Since there hasn't been any update from the previous commenter for a month, I would like to pick this up. I plan to update the context menu icons to match the standard icons used in the Sidebar and Map buttons for consistency. Could you please assign this to me?

**Comment by HolgerJeromin** [comment]
> Could you please assign this to me?

We do not work with assignments.
Just go ahead

**Comment by pablobm** [comment]
Specific questions raised at https://github.com/openstreetmap/openstreetmap-website/pull/6571:

- What icons would be appropriate for "from" and "to", that can be used in both contexts?
	- "Play" and "stop" icons are available in Bootstrap and can be used in the context menu.
	- However they might be a confusing choice for users as action icons (or are they?).
- Currently the context menu uses Bootstrap icons, but the map controls use inlined SVGs.
	- What would work, technically and visually, for both the "add note" and "query features" actions?

**Comment by hlfan** [comment]
Has #6571 resolved this?

**Comment by pablobm** [comment]
@hlfan - My view is that it has improved the situation, but not resolved it. Summarising from my comment at https://github.com/openstreetmap/openstreetmap-website/pull/6571#issuecomment-3606481137, my opinion is:

1. The "play" and "stop" icons don't necessarily convey "route from here" and "route to here".
1. The "add note" icons are different in the context menu and the sidebar.
1. The "query" icons are different in the context menu and the sidebar.

It might be worth creating separate issues for each of these, as it's not necessarily practical to solve them in a single go.

**Comment by aNsHuL5217** [comment]
I totally agree. As we discussed during the PR, sticking to the available Bootstrap classes was the cleanest technical path for now, even if it meant the icons aren't a 1:1 match with the sidebar SVGs. Forcing that match would've required either a messy CSS override or a larger refactor that didn't feel right at the time.

Since the remaining work is really about nailing the design metaphors (like finding a better fit than the "Play/Stop" icons), it definitely makes sense to track that separately.

I'll go ahead and open those new issues now to keep this organized, and then we can close this one out.

**Comment by hlfan** [comment]
> Since the remaining work is really about nailing the design metaphors (like finding a better fit than the "Play/Stop" icons), it definitely makes sense to track that separately.

Well, that has already been a topic in https://github.com/openstreetmap/openstreetmap-website/issues/929#issuecomment-78864019; its main concern is resolved, so why not move the discussion there?

**Comment by aNsHuL5217** [comment]
> > Since the remaining work is really about nailing the design metaphors (like finding a better fit than the "Play/Stop" icons), it definitely makes sense to track that separately.
> 
> Well, that has already been a topic in [#929 (comment)](https://github.com/openstreetmap/openstreetmap-website/issues/929#issuecomment-78864019); its main concern is resolved, so why not move the discussion there?

@hlfan , I had just hit "Create" on the new issue right before seeing your comment!

I have closed that new issue in favor of moving the discussion to #929 as you suggested.

I did leave #6681 open, as that focuses specifically on the technical implementation of the "Add note/Query" icons (Bootstrap vs SVG), which seems distinct from the route marker design discussion.

**Comment by hlfan** [comment]
Well then I think we can close this one.
